# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculatorGUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(321, 319)
        self.input = QtWidgets.QLineEdit(Calculator)
        self.input.setGeometry(QtCore.QRect(10, 20, 301, 31))
        self.input.setText("")
        self.input.setObjectName("input")
        self.num7 = QtWidgets.QPushButton(Calculator)
        self.num7.setGeometry(QtCore.QRect(10, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.num7.setFont(font)
        self.num7.setObjectName("num7")
        self.num8 = QtWidgets.QPushButton(Calculator)
        self.num8.setGeometry(QtCore.QRect(70, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.num8.setFont(font)
        self.num8.setObjectName("num8")
        self.num9 = QtWidgets.QPushButton(Calculator)
        self.num9.setGeometry(QtCore.QRect(130, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.num9.setFont(font)
        self.num9.setObjectName("num9")
        self.num6 = QtWidgets.QPushButton(Calculator)
        self.num6.setGeometry(QtCore.QRect(130, 130, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.num6.setFont(font)
        self.num6.setObjectName("num6")
        self.num4 = QtWidgets.QPushButton(Calculator)
        self.num4.setGeometry(QtCore.QRect(10, 130, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.num4.setFont(font)
        self.num4.setObjectName("num4")
        self.num5 = QtWidgets.QPushButton(Calculator)
        self.num5.setGeometry(QtCore.QRect(70, 130, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.num5.setFont(font)
        self.num5.setObjectName("num5")
        self.num3 = QtWidgets.QPushButton(Calculator)
        self.num3.setGeometry(QtCore.QRect(130, 190, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.num3.setFont(font)
        self.num3.setObjectName("num3")
        self.num1 = QtWidgets.QPushButton(Calculator)
        self.num1.setGeometry(QtCore.QRect(10, 190, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.num1.setFont(font)
        self.num1.setObjectName("num1")
        self.num2 = QtWidgets.QPushButton(Calculator)
        self.num2.setGeometry(QtCore.QRect(70, 190, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.num2.setFont(font)
        self.num2.setObjectName("num2")
        self.num0 = QtWidgets.QPushButton(Calculator)
        self.num0.setGeometry(QtCore.QRect(70, 250, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.num0.setFont(font)
        self.num0.setObjectName("num0")
        self.decimal = QtWidgets.QPushButton(Calculator)
        self.decimal.setGeometry(QtCore.QRect(10, 250, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.decimal.setFont(font)
        self.decimal.setObjectName("decimal")
        self.equal = QtWidgets.QPushButton(Calculator)
        self.equal.setGeometry(QtCore.QRect(260, 250, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.equal.setFont(font)
        self.equal.setObjectName("equal")
        self.rightpar = QtWidgets.QPushButton(Calculator)
        self.rightpar.setGeometry(QtCore.QRect(260, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.rightpar.setFont(font)
        self.rightpar.setObjectName("rightpar")
        self.leftpar = QtWidgets.QPushButton(Calculator)
        self.leftpar.setGeometry(QtCore.QRect(200, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.leftpar.setFont(font)
        self.leftpar.setObjectName("leftpar")
        self.add = QtWidgets.QPushButton(Calculator)
        self.add.setGeometry(QtCore.QRect(200, 130, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.add.setFont(font)
        self.add.setObjectName("add")
        self.subtract = QtWidgets.QPushButton(Calculator)
        self.subtract.setGeometry(QtCore.QRect(260, 130, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.subtract.setFont(font)
        self.subtract.setObjectName("subtract")
        self.multiply = QtWidgets.QPushButton(Calculator)
        self.multiply.setGeometry(QtCore.QRect(200, 190, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.multiply.setFont(font)
        self.multiply.setObjectName("multiply")
        self.divide = QtWidgets.QPushButton(Calculator)
        self.divide.setGeometry(QtCore.QRect(260, 190, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.divide.setFont(font)
        self.divide.setObjectName("divide")
        self.clear = QtWidgets.QPushButton(Calculator)
        self.clear.setGeometry(QtCore.QRect(130, 250, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        self.exponent = QtWidgets.QPushButton(Calculator)
        self.exponent.setGeometry(QtCore.QRect(200, 250, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.exponent.setFont(font)
        self.exponent.setObjectName("exponent")

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Calculator"))
        self.num7.setText(_translate("Calculator", "7"))
        self.num8.setText(_translate("Calculator", "8"))
        self.num9.setText(_translate("Calculator", "9"))
        self.num6.setText(_translate("Calculator", "6"))
        self.num4.setText(_translate("Calculator", "4"))
        self.num5.setText(_translate("Calculator", "5"))
        self.num3.setText(_translate("Calculator", "3"))
        self.num1.setText(_translate("Calculator", "1"))
        self.num2.setText(_translate("Calculator", "2"))
        self.num0.setText(_translate("Calculator", "0"))
        self.decimal.setText(_translate("Calculator", "."))
        self.equal.setText(_translate("Calculator", "="))
        self.rightpar.setText(_translate("Calculator", ")"))
        self.leftpar.setText(_translate("Calculator", "("))
        self.add.setText(_translate("Calculator", "+"))
        self.subtract.setText(_translate("Calculator", "-"))
        self.multiply.setText(_translate("Calculator", "*"))
        self.divide.setText(_translate("Calculator", "/"))
        self.clear.setText(_translate("Calculator", "clear"))
        self.exponent.setText(_translate("Calculator", "^"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QDialog()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())

